CITIES:
  EAST:
  - Columbia
  - San Jose
  - Jacksonville
  - Des Moines
  MIDWEST:
  - Columbus
  - Salt Lake City
  - Tulsa
  - Jacksonville
  SOUTH:
  - Columbia
  - San Jose
  - Hartford
  - Columbus
  WEST:
  - Salt Lake City
  - Hartford
  - Tulsa
  - Des Moines
DATA_DIR: data
DEBUG:
  VERBOSE: true
MODEL_CONFIG:
  NUM_SIMS: 2
  RANDOM_FACTOR: 200
TEAMS:
  EAST:
  - Michigan
  - Texas Southern
  - LSU
  - St. Bonaventure
  - Colorado
  - Georgetown
  - Florida St.
  - UNC Greensboro
  - BYU
  - UCLA
  - Texas
  - Abilene Christian
  - Connecticut
  - Maryland
  - Alabama
  - Iona
  MIDWEST:
  - Illinois
  - Drexel
  - Loyola Chicago
  - Georgia Tech
  - Tennessee
  - Oregon St.
  - Oklahoma St.
  - Liberty
  - San Diego St.
  - Syracuse
  - West Virginia
  - Morehead St.
  - Clemson
  - Rutgers
  - Houston
  - Cleveland St.
  SOUTH:
  - Baylor
  - Hartford
  - North Carolina
  - Wisconsin
  - Villanova
  - Winthrop
  - Purdue
  - North Texas
  - Texas Tech
  - Utah St.
  - Arkansas
  - Colgate
  - Florida
  - Virginia Tech
  - Ohio St.
  - Oral Roberts
  WEST:
  - Gonzaga
  - Norfolk St.
  - Oklahoma
  - Missouri
  - Creighton
  - UC Santa Barbara
  - Virginia
  - Ohio
  - USC
  - Drake
  - Kansas
  - Eastern Washington
  - Oregon
  - VCU
  - Iowa
  - Grand Canyon
version: '3'
