CITIES:
  EAST:
  - Columbia
  - San Jose
  - Jacksonville
  - Des Moines
  MIDWEST:
  - Columbus
  - Salt Lake City
  - Tulsa
  - Jacksonville
  SOUTH:
  - Columbia
  - San Jose
  - Hartford
  - Columbus
  WEST:
  - Salt Lake City
  - Hartford
  - Tulsa
  - Des Moines
DATA_DIR: data
DEBUG:
  VERBOSE: true
MODEL_CONFIG:
  NUM_SIMS: 2
  RANDOM_FACTOR: 200
TEAMS:
  EAST:
  - Baylor
  - Norfolk St.
  - North Carolina
  - Marquette
  - Saint Mary's
  - Wyoming
  - UCLA
  - Akron
  - Texas
  - Virginia Tech
  - Purdue
  - Yale
  - Murray St.
  - San Francisco
  - Kentucky
  - Saint Peter's
  MIDWEST:
  - Kansas
  - Texas Southern
  - San Diego St.
  - Creighton
  - Iowa
  - Richmond
  - Providence
  - South Dakota St.
  - LSU
  - Iowa St.
  - Wisconsin
  - Colgate
  - USC
  - Miami FL
  - Auburn
  - Jacksonville St.
  SOUTH:
  - Arizona
  - Bryant
  - Seton Hall
  - TCU
  - Houston
  - UAB
  - Illinois
  - Chattanooga
  - Colorado St.
  - Michigan
  - Tennessee
  - Longwood
  - Ohio St.
  - Loyola Chicago
  - Villanova
  - Delaware
  WEST:
  - Gonzaga
  - Georgia St.
  - Boise St.
  - Memphis
  - Connecticut
  - New Mexico St.
  - Arkansas
  - Vermont
  - Alabama
  - Notre Dame
  - Texas Tech
  - Montana St.
  - Michigan St.
  - Davidson
  - Duke
  - Cal St. Fullerton
version: '3'
