CITIES:
  EAST:
  - Columbia
  - San Jose
  - Jacksonville
  - Des Moines
  MIDWEST:
  - Columbus
  - Salt Lake City
  - Tulsa
  - Jacksonville
  SOUTH:
  - Columbia
  - San Jose
  - Hartford
  - Columbus
  WEST:
  - Salt Lake City
  - Hartford
  - Tulsa
  - Des Moines
DATA_DIR: data
DEBUG:
  VERBOSE: true
MODEL_CONFIG:
  NUM_SIMS: 50
  RANDOM_FACTOR: 150
TEAMS:
  EAST:
  - Purdue
  - Marquette
  - Duke
  - Tennessee
  - Kentucky
  - Memphis
  - Kansas State
  - Michigan State
  - Providence
  - Southern California
  - Florida Atlantic
  - Oral Roberts
  - Louisiana-Lafayette
  - Vermont
  - Montana State
  - Texas Southern
  - Fairleigh Dickinson
  MIDWEST:
  - Houston
  - Texas
  - Indiana
  - Texas A&M
  - Iowa State
  - Xavier
  - Auburn
  - Iowa
  - Miami (FL)
  - Penn State
  - Drake
  - Pittsburgh
  - Kent State
  - Colgate
  - Kennesaw State
  - Northern Kentucky
  - Mississippi State
  SOUTH:
  - Alabama
  - Arizona
  - Baylor
  - Creighton
  - San Diego State
  - Virginia
  - Maryland
  - West Virginia
  - Utah State
  - Missouri
  - North Carolina State
  - College of Charleston
  - Furman
  - UC-Santa Barbara
  - Princeton
  - Texas A&M-Corpus Christi
  - Southeast Missouri State
  WEST:
  - Kansas
  - Gonzaga
  - UCLA
  - Connecticut
  - Texas Christian
  - Saint Mary's (CA)
  - Arkansas
  - Illinois
  - Boise State
  - Northwestern
  - Virginia Commonwealth
  - Arizona State
  - Nevada
  - Iona
  - Grand Canyon
  - North Carolina-Asheville
  - Howard
version: '3'
